spring.datasource.url=jdbc:mysql://sql5.freesqldatabase.com:3306/sql5823086?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=sql5823086
spring.datasource.password=COLOQUE_A_SENHA_AQUI

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
